#!/usr/bin/env bash
#
# build-happy-bundle.sh — produce a portable happy bundle that every distribution
# channel (npm, GitHub tarball, Tauri desktop, Docker) can ship next to 1agents.
#
# Layout produced (default OUT=build):
#   build/happy-cli/   dist/ + bin/ + package.json + package-lock.json
#                      [+ node_modules if BUNDLE_NODE_MODULES=1]
#   build/adapter/     copy of the repo's RPC glue (adapter/)
#   build/happy        launcher: npm ci (locked) if needed, then exec node
#
# package-lock.json is always generated so install-time `npm ci --omit=dev`
# pins production dependency versions. node_modules are NOT prebundled by
# default (set BUNDLE_NODE_MODULES=1 for offline desktop bundles).
#
# Usage:   scripts/build-happy-bundle.sh [OUT_DIR]   (default: build)
# Env:     SKIP_BUILD=1            reuse modules/happy-cli/dist
#          BUNDLE_NODE_MODULES=1   pre-install production deps into the stage
#          KEEP_AGENT_SDK_NATIVE=1  keep Claude Agent SDK native packages
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/build}"
HAPPY_SRC="$ROOT/modules/happy-cli"
STAGE="$OUT/happy-cli"

echo "=== happy bundle: root=$ROOT out=$OUT"

if [ ! -f "$HAPPY_SRC/package.json" ]; then
    echo "=== Initializing happy-cli submodule..."
    git -C "$ROOT" submodule update --init modules/happy-cli
fi

command -v corepack >/dev/null 2>&1 && corepack enable >/dev/null 2>&1 || true

if [ "${SKIP_BUILD:-}" != "1" ]; then
    echo "=== Building happy-cli (pnpm install + build)..."
    ( cd "$HAPPY_SRC" && pnpm install && pnpm run build )
else
    echo "=== SKIP_BUILD=1 — reusing existing $HAPPY_SRC/dist"
fi
[ -f "$HAPPY_SRC/dist/index.mjs" ] || { echo "✗ happy-cli not built: dist/index.mjs missing" >&2; exit 1; }

echo "=== Staging happy bundle -> $STAGE"
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp -r "$HAPPY_SRC/dist" "$STAGE/dist"
cp -r "$HAPPY_SRC/bin" "$STAGE/bin"
cp "$HAPPY_SRC/package.json" "$STAGE/package.json"

prune_agent_sdk_native() {
    local dir="$1"
    if [ "${KEEP_AGENT_SDK_NATIVE:-}" = "1" ]; then
        return 0
    fi
    echo "=== Pruning Claude Agent SDK native runtime (~224MB)..."
    rm -rf "$dir"/node_modules/@anthropic-ai/claude-agent-sdk-*
}

# Always generate a package-lock.json for reproducible install-time `npm ci`.
# --ignore-scripts skips unpack-tools.cjs (session tools the daemon never needs).
echo "=== Generating happy-cli package-lock.json (production, ignore-scripts)..."
(
  cd "$STAGE"
  # Full install creates a complete lockfile; we may drop node_modules afterward.
  npm install --omit=dev --ignore-scripts --no-audit --no-fund
)
if [ ! -f "$STAGE/package-lock.json" ]; then
    echo "✗ failed to generate package-lock.json for happy-cli" >&2
    exit 1
fi
echo "=== package-lock.json ready ($(wc -c < "$STAGE/package-lock.json") bytes)"

if [ "${BUNDLE_NODE_MODULES:-0}" = "1" ]; then
    echo "=== BUNDLE_NODE_MODULES=1 — keeping production node_modules in stage"
    prune_agent_sdk_native "$STAGE"
else
    echo "=== Removing staged node_modules (install via npm ci at postinstall / first launch)"
    rm -rf "$STAGE/node_modules"
fi

echo "=== Bundling RPC adapter -> $OUT/adapter"
rm -rf "$OUT/adapter"
cp -r "$ROOT/adapter" "$OUT/adapter"

cat > "$OUT/happy" <<'LAUNCH'
#!/bin/sh
# 1agents bundled happy launcher (generated by build-happy-bundle.sh).
HERE="$(cd "$(dirname "$0")" && pwd)"
CLI="$HERE/happy-cli"
export HAPPY_RPC_ADAPTER_ENTRY="${HAPPY_RPC_ADAPTER_ENTRY:-$HERE/adapter/rpc/index.mjs}"

if [ ! -d "$CLI/node_modules" ]; then
  echo "[happy] Installing production dependencies (locked)..." >&2
  if ! command -v npm >/dev/null 2>&1; then
    echo "[happy] npm not found; cannot install happy-cli dependencies." >&2
    exit 1
  fi
  if [ -f "$CLI/package-lock.json" ]; then
    ( cd "$CLI" && npm ci --omit=dev --ignore-scripts --no-audit --no-fund ) || exit 1
  else
    ( cd "$CLI" && npm install --omit=dev --ignore-scripts --no-audit --no-fund ) || exit 1
  fi
  # Drop unused Claude Agent SDK native binaries if present.
  rm -rf "$CLI"/node_modules/@anthropic-ai/claude-agent-sdk-* 2>/dev/null || true
fi

exec node "$CLI/bin/happy.mjs" "$@"
LAUNCH
chmod +x "$OUT/happy"

echo "=== happy bundle ready:"
du -sh "$STAGE" "$OUT/adapter" 2>/dev/null || true
ls -la "$STAGE/package-lock.json" 2>/dev/null || true
echo "    launcher: $OUT/happy"
if [ ! -d "$STAGE/node_modules" ]; then
    echo "    note: node_modules deferred (npm ci --omit=dev at postinstall / first launch)"
fi
